import Link from "next/link"
import Head from "next/head"
import { useEffect, useState } from 'react'
import { Paper, Typography, Link as MaterialLink } from '@mui/material'
import { Pool } from 'market-sdk'

import WalletConnectButton from '../components/WalletSelector/Button'

import { useEthers } from '../hooks/useEthers'
import { useMarket } from '../hooks/useMarket'

import styles from '../styles/Home.module.css'

function Home(){
  const { network } = useEthers();
  const { sdk } = useMarket();

  const [pools, setPools] = useState<Pool[]>();

  useEffect(() => {
    if(!sdk){
      return;
    }
    sdk?.poolDirectory.v1!.getAllPools().then(setPools);
  }, [sdk]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography variant="h3">
          Market SDK React Example
        </Typography>

        <WalletConnectButton />

        <Typography variant="body1">
          Selected network: {network.chainId}
        </Typography>
        
        <Typography variant="h4">
          Pools
        </Typography>

        <pre>
          {
            pools && pools.map((pool, i) => (
              <Link key={i} href={`/pools/${i}`} passHref>
                <MaterialLink underline="hover">
                  <Paper sx={{ padding: 2, margin: 2 }}>
                    <Typography variant="h6">{pool.name}</Typography>
                    <Typography variant="body1">Creator: {pool.creator}</Typography>
                    <Typography variant="body1">Comptroller: {pool.comptroller.address}</Typography>
                  </Paper>
                </MaterialLink>
              </Link>
            ))
          }
        </pre>
      </main>

      <footer className={styles.footer}>
        Copyright © market.xyz
      </footer>
    </div>
  )
}

export default Home;
